--The Winged Dragon of Ra
Duel.LoadScript("c421.lua")
local s,id=GetID()
function s.initial_effect(c)
	--Summon with 3 Tribute
	local e1=aux.AddNormalSummonProcedure(c,true,false,3,3)
	local e2=aux.AddNormalSetProcedure(c,true,false,3,3)
	--Summon with 3 Tribute
	--c:SetUniqueOnField(1,1,190000013)
	--local e1=Effect.CreateEffect(c)
	--e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	--e1:SetType(EFFECT_TYPE_SINGLE)
	--e1:SetCode(EFFECT_LIMIT_SUMMON_PROC)
	--e1:SetCondition(s.sumoncon)
	--e1:SetOperation(s.sumonop)
	--e1:SetValue(SUMMON_TYPE_ADVANCE)
	--c:RegisterEffect(e1)
	--local e2=Effect.CreateEffect(c)
	--e2:SetType(EFFECT_TYPE_SINGLE)
	--e2:SetCode(EFFECT_LIMIT_SET_PROC)
	--e2:SetCondition(s.setcon)
	--c:RegisterEffect(e2)
	--Cannot be Set
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_CANNOT_TURN_SET)
	e3:SetRange(LOCATION_MZONE)
	e3:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e3:SetTarget(s.cannotsettg)
	c:RegisterEffect(e3)
	--Summon Cannot be Negated
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetCode(EFFECT_CANNOT_DISABLE_SUMMON)
	e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	c:RegisterEffect(e4)
	--Summon Success: Effects of non-DIVINE monsters Cannot be Activated
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e5:SetCode(EVENT_SUMMON_SUCCESS)
	e5:SetOperation(s.sumnotnegatedop)
	c:RegisterEffect(e5)
 	--Original ATK/DEF
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE)
	e6:SetCode(EFFECT_MATERIAL_CHECK)
	e6:SetValue(s.materialvalcheck)
	c:RegisterEffect(e6)
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e7:SetCode(EVENT_SUMMON_SUCCESS)
	e7:SetOperation(s.atkdefop)
	c:RegisterEffect(e7)
	--Cannot be Tributed by Opponent
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_SINGLE)
	e8:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e8:SetRange(LOCATION_MZONE)
	e8:SetCode(EFFECT_UNRELEASABLE_SUM)
	e8:SetValue(s.nottributedval)
	c:RegisterEffect(e8)
	local e9=e8:Clone()
	e9:SetCode(EFFECT_UNRELEASABLE_NONSUM)
	e9:SetCondition(s.nottributedcon)
	c:RegisterEffect(e9)
    --Cannot Switch Controller
	local e10=Effect.CreateEffect(c)
	e10:SetType(EFFECT_TYPE_SINGLE)
	e10:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e10:SetRange(LOCATION_MZONE)
	e10:SetCode(EFFECT_CANNOT_CHANGE_CONTROL)
	c:RegisterEffect(e10)
	--Cannot be Targeted by the effects of Spell/Trap Cards and non-DIVINE monsters
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_SINGLE)
	e11:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e11:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e11:SetRange(LOCATION_MZONE)
	e11:SetValue(s.notargetedval)
	c:RegisterEffect(e11)
    --Cannot be Destroyed by the effects of Spell/Trap Cards and non-DIVINE monsters
	local e12=Effect.CreateEffect(c)
	e12:SetType(EFFECT_TYPE_SINGLE)
	e12:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e12:SetRange(LOCATION_MZONE)
	e12:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e12:SetValue(s.nodestroyedval)
	c:RegisterEffect(e12)
	--Cannot be Removed
	local e13=Effect.CreateEffect(c)
	e13:SetType(EFFECT_TYPE_SINGLE)
	e13:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e13:SetRange(LOCATION_MZONE)
	e13:SetCode(EFFECT_CANNOT_REMOVE)
	c:RegisterEffect(e13)
	--Cannot Send to Grave
	local e14=Effect.CreateEffect(c)
	e14:SetType(EFFECT_TYPE_SINGLE)
	e14:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e14:SetRange(LOCATION_MZONE)
	e14:SetCode(EFFECT_CANNOT_TO_GRAVE)
	e14:SetCondition(s.togravecon)
	c:RegisterEffect(e14)
	--Cannot Return to Hand
	local e15=Effect.CreateEffect(c)
	e15:SetType(EFFECT_TYPE_SINGLE)
	e15:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e15:SetRange(LOCATION_MZONE)
	e15:SetCode(EFFECT_CANNOT_TO_HAND)
	c:RegisterEffect(e15)
	--Cannot Return to Deck
	local e16=Effect.CreateEffect(c)
	e16:SetType(EFFECT_TYPE_SINGLE)
	e16:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e16:SetRange(LOCATION_MZONE)
	e16:SetCode(EFFECT_CANNOT_TO_DECK)
	c:RegisterEffect(e16)
	--Effect Cannot be Negated
	local e17=Effect.CreateEffect(c)
	e17:SetType(EFFECT_TYPE_SINGLE)
	e17:SetCode(EFFECT_CANNOT_DISABLE)
	e17:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e17)
	--Change Battle Position in Turn that is Normal Summoned
	--local e18=Effect.CreateEffect(c)
	--e18:SetDescription(aux.Stringid(190000013,5))
	--e18:SetCategory(CATEGORY_POSITION)
	--e18:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	--e18:SetType(EFFECT_TYPE_IGNITION)
	--e18:SetRange(LOCATION_MZONE)
	--e18:SetCountLimit(1)
	--e18:SetCost(s.changebattlepositioncost)
	--e18:SetOperation(s.changebattlepositionop)
	--c:RegisterEffect(e18)
	--
	local e19=Effect.CreateEffect(c)
	e19:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e19:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e19:SetCode(EVENT_SUMMON_SUCCESS)
	e19:SetOperation(s.changebattlepositionop2)
	c:RegisterEffect(e19)
	--If Special Summoned: Send to Grave
	local e20=Effect.CreateEffect(c)
	e20:SetDescription(aux.Stringid(190000013,6))
	e20:SetCategory(CATEGORY_TOGRAVE)
	e20:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e20:SetRange(LOCATION_MZONE)
	e20:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e20:SetCountLimit(1)
	e20:SetCode(EVENT_PHASE+PHASE_END)
	e20:SetCondition(s.specialsumtogravecon)
	e20:SetTarget(s.specialsumtogravetg)
	e20:SetOperation(s.specialsumtograveop)
	c:RegisterEffect(e20)
	--Change Battle Target when Special Summoned in Defense Position
	local e21=Effect.CreateEffect(c)
	e21:SetDescription(aux.Stringid(190000013,7))
	e21:SetProperty(EFFECT_FLAG_NO_TURN_RESET)
	e21:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e21:SetCode(EVENT_BE_BATTLE_TARGET)
	e21:SetRange(LOCATION_MZONE)
	e21:SetCountLimit(1)
	e21:SetCondition(s.changebattletargetcon)
	e21:SetOperation(s.changebattletargetop)
	c:RegisterEffect(e21)
	--Point-to-Point Transfer 2
	local e007=Effect.CreateEffect(c)
	e007:SetDescription(aux.Stringid(190000013,8))
	e007:SetCategory(CATEGORY_RECOVER)
	e007:SetType(EFFECT_TYPE_IGNITION)
	e007:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e007:SetCode(EVENT_FREE_CHAIN)
	e007:SetRange(LOCATION_MZONE)
	e007:SetCountLimit(1)
	e007:SetCondition(s.condition11)
	e007:SetTarget(s.target11)
	e007:SetOperation(s.activate22)
	c:RegisterEffect(e007)
	--Point-to-Point Transfer 1
	local e006=Effect.CreateEffect(c)
	e006:SetDescription(aux.Stringid(190000013,0))
	e006:SetCategory(CATEGORY_ATKCHANGE)
	e006:SetType(EFFECT_TYPE_IGNITION)
	e006:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e006:SetCode(EVENT_FREE_CHAIN)
	e006:SetRange(LOCATION_MZONE)
	e006:SetCountLimit(1)
	e006:SetCost(s.atkcost1)
	e006:SetOperation(s.atkop1)
	c:RegisterEffect(e006)
	--Point-to-Point Transfer
	local e22=Effect.CreateEffect(c)
	e22:SetDescription(aux.Stringid(190000013,0))
	e22:SetCategory(CATEGORY_ATKCHANGE)
	e22:SetType(EFFECT_TYPE_IGNITION+EFFECT_TYPE_QUICK_O)
	e22:SetCode(EVENT_FREE_CHAIN)
	e22:SetHintTiming(TIMING_DAMAGE_STEP)
	e22:SetRange(LOCATION_MZONE)
	e22:SetCountLimit(1)
	e22:SetCost(s.pointtopointcost)
	e22:SetOperation(s.pointtopointop)
	c:RegisterEffect(e22)
	--Tribute-to-Point Transfer
	local e23=Effect.CreateEffect(c)
	e23:SetDescription(aux.Stringid(190000013,1))
	e23:SetCategory(CATEGORY_ATKCHANGE)
	e23:SetType(EFFECT_TYPE_IGNITION+EFFECT_TYPE_QUICK_O)
	e23:SetCode(EVENT_FREE_CHAIN)
	e23:SetHintTiming(TIMING_DAMAGE_STEP)
	e23:SetRange(LOCATION_MZONE)
	e23:SetCountLimit(1)
	e23:SetCost(s.tributetopointcost)
	e23:SetOperation(s.tributetopointop)
	c:RegisterEffect(e23)
	--Instant Attack
	local e24=Effect.CreateEffect(c)
	e24:SetDescription(aux.Stringid(190000013,2))
	e24:SetType(EFFECT_TYPE_IGNITION+EFFECT_TYPE_QUICK_O)
	e24:SetCode(EVENT_FREE_CHAIN)
	e24:SetHintTiming(TIMING_BATTLE_PHASE)
	e24:SetRange(LOCATION_MZONE)
	e24:SetCountLimit(1)
	e24:SetCost(s.iacost)
	e24:SetOperation(s.iaop)
	c:RegisterEffect(e24)
	--"De-Fusion" Point-to-Point Transfer reverse
	local e25=Effect.CreateEffect(c)
	e25:SetDescription(aux.Stringid(190000013,3))
	e25:SetCategory(CATEGORY_RECOVER+CATEGORY_ATKCHANGE)
	e25:SetType(EFFECT_TYPE_IGNITION+EFFECT_TYPE_QUICK_O)
	e25:SetCode(EVENT_FREE_CHAIN)
	e25:SetHintTiming(TIMING_DAMAGE_STEP)
	e25:SetRange(LOCATION_MZONE)
	e25:SetCountLimit(1)
	e25:SetCost(s.defusioncost)
	e25:SetOperation(s.defusionop)
	c:RegisterEffect(e25)
	--God Phoenix
	local e26=Effect.CreateEffect(c)
	e26:SetDescription(aux.Stringid(190000013,4))
	e26:SetCategory(CATEGORY_TOKEN)
	e26:SetType(EFFECT_TYPE_IGNITION+EFFECT_TYPE_QUICK_O)
	e26:SetCode(EVENT_FREE_CHAIN)
	e26:SetHintTiming(TIMING_DAMAGE_STEP)
	e26:SetRange(LOCATION_MZONE)
	e26:SetCountLimit(1)
	e26:SetCost(s.godphoenixcost)
	e26:SetOperation(s.godphoenixop)
	c:RegisterEffect(e26)
	--ATK/DEF effects only affect until the End Phase
	local e27=Effect.CreateEffect(c)
	e27:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e27:SetProperty(EFFECT_FLAG_REPEAT)
	e27:SetRange(LOCATION_MZONE)
	e27:SetCode(EVENT_PHASE+PHASE_END)
	e27:SetCountLimit(1)
	e27:SetOperation(s.atkdefresetop)
	c:RegisterEffect(e27)
	--"Cryomancer of the Ice Barrier" effect only affects until the End Phase
	local e28=Effect.CreateEffect(c)
	e28:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e28:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e28:SetRange(LOCATION_MZONE)
	e28:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e28:SetCountLimit(1)
	e28:SetCondition(s.cryomancercon)
	e28:SetOperation(s.cryomancerop)
	c:RegisterEffect(e28)
	--"Reptilianne Gorgon" effect only affects until the End Phase
	local e29=Effect.CreateEffect(c)
	e29:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e29:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e29:SetRange(LOCATION_MZONE)
	e29:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e29:SetCountLimit(1)
	e29:SetCondition(s.gorgoncon)
	e29:SetOperation(s.gorgonop)
	c:RegisterEffect(e29)
	--"Harpie Lady 3" effect only affects until the End Phase
	local e30=Effect.CreateEffect(c)
	e30:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e30:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e30:SetRange(LOCATION_MZONE)
	e30:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e30:SetCountLimit(1)
	e30:SetCondition(s.harpiecon)
	e30:SetOperation(s.harpieop)
	c:RegisterEffect(e30)
	--"Gora Turtle" effect only affects until the End Phase
	local e31=Effect.CreateEffect(c)
	e31:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e31:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e31:SetRange(LOCATION_MZONE)
	e31:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e31:SetCountLimit(1)
	e31:SetCondition(s.goraturtlecon)
	e31:SetOperation(s.goraturtleop)
	c:RegisterEffect(e31)
	--"Defender of the Ice Barrier" effect only affects until the End Phase
	local e32=Effect.CreateEffect(c)
	e32:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e32:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e32:SetRange(LOCATION_MZONE)
	e32:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e32:SetCountLimit(1)
	e32:SetCondition(s.defendercon)
	e32:SetOperation(s.defenderop)
	c:RegisterEffect(e32)
	--"Photon Delta Wing" effect only affects until the End Phase
	local e33=Effect.CreateEffect(c)
	e33:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e33:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e33:SetRange(LOCATION_MZONE)
	e33:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e33:SetCountLimit(1)
	e33:SetCondition(s.deltawingcon)
	e33:SetOperation(s.deltawingop)
	c:RegisterEffect(e33)
	--"Thousand-Eyes Restrict" effect only affects until the End Phase
	local e34=Effect.CreateEffect(c)
	e34:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e34:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e34:SetRange(LOCATION_MZONE)
	e34:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e34:SetCountLimit(1)
	e34:SetCondition(s.thousandeyescon)
	e34:SetOperation(s.thousandeyesop)
	c:RegisterEffect(e34)
	--"Level Limit - Area B" effect only affects until the End Phase
	local e35=Effect.CreateEffect(c)
	e35:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e35:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e35:SetRange(LOCATION_MZONE)
	e35:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e35:SetCountLimit(1)
	e35:SetCondition(s.levelareacon)
	e35:SetOperation(s.levelareaop)
	c:RegisterEffect(e35)
	--"Swords of Concealing Light" effect only affects until the End Phase
	local e36=Effect.CreateEffect(c)
	e36:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e36:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e36:SetRange(LOCATION_MZONE)
	e36:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e36:SetCountLimit(1)
	e36:SetCondition(s.concealinglightcon)
	e36:SetOperation(s.concealinglightop)
	c:RegisterEffect(e36)
	--"Spiders' Lair" effect only affects until the End Phase
	local e37=Effect.CreateEffect(c)
	e37:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e37:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e37:SetRange(LOCATION_MZONE)
	e37:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e37:SetCountLimit(1)
	e37:SetCondition(s.spiderslaircon)
	e37:SetOperation(s.spiderslairop)
	c:RegisterEffect(e37)
	--"Messenger of Peace" effect only affects until the End Phase
	local e38=Effect.CreateEffect(c)
	e38:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e38:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e38:SetRange(LOCATION_MZONE)
	e38:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e38:SetCountLimit(1)
	e38:SetCondition(s.messengercon)
	e38:SetOperation(s.messengerop)
	c:RegisterEffect(e38)
	--"Swords of Revealing Light" effect only affects until the End Phase
	local e39=Effect.CreateEffect(c)
	e39:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e39:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e39:SetRange(LOCATION_MZONE)
	e39:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e39:SetCountLimit(1)
	e39:SetCondition(s.revealinglightcon)
	e39:SetOperation(s.revealinglightop)
	c:RegisterEffect(e39)
	--"Swords of Burning Light" effect only affects until the End Phase
	local e40=Effect.CreateEffect(c)
	e40:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e40:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e40:SetRange(LOCATION_MZONE)
	e40:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e40:SetCountLimit(1)
	e40:SetCondition(s.burninglightcon)
	e40:SetOperation(s.burninglightop)
	c:RegisterEffect(e40)
	--"Final Attack Orders" effect only affects until the End Phase
	local e41=Effect.CreateEffect(c)
	e41:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e41:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e41:SetRange(LOCATION_MZONE)
	e41:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e41:SetCountLimit(1)
	e41:SetCondition(s.finalorderscon)
	e41:SetOperation(s.finalordersop)
	c:RegisterEffect(e41)
	--"Morphtronic Bind" effect only affects until the End Phase
	local e42=Effect.CreateEffect(c)
	e42:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e42:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e42:SetRange(LOCATION_MZONE)
	e42:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e42:SetCountLimit(1)
	e42:SetCondition(s.morphtronicbindcon)
	e42:SetOperation(s.morphtronicbindop)
	c:RegisterEffect(e42)
	--"Gravity Bind" effect only affects until the End Phase
	local e43=Effect.CreateEffect(c)
	e43:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e43:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e43:SetRange(LOCATION_MZONE)
	e43:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e43:SetCountLimit(1)
	e43:SetCondition(s.gravitybindcon)
	e43:SetOperation(s.gravitybindop)
	c:RegisterEffect(e43)
end
function s.atkcost1(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLP(tp)>100 end
	local lp=Duel.GetLP(tp)
	Original_ATK_DEF=e:GetHandler():GetAttack()+(lp-100)
	e:SetLabel(Original_ATK_DEF)
	Duel.PayLPCost(tp,lp-100)
end
function s.atkop1(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsFaceup() and c:IsRelateToEffect(e) then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e1:SetRange(LOCATION_MZONE)
		e1:SetCode(EFFECT_SET_BASE_ATTACK)
		e1:SetReset(RESET_EVENT+0x1fe0000)
		e1:SetValue(e:GetLabel())
		c:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_SET_BASE_DEFENSE)
		c:RegisterEffect(e2)
	end
end
function s.condition11(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetLP(tp)>=100 and e:GetHandler():GetAttack() >= 5000
end
function s.target11(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	local tg=e:GetHandler()
	if chk==0 then return Duel.GetLP(tp)>=100 and e:GetHandler():GetAttack() >= 5000 end
	local lp=e:GetHandler():GetAttack()-5000
	Duel.SetOperationInfo(0,CATEGORY_RECOVER,nil,0,tp,lp)
end
function s.activate22(e,tp,eg,ep,ev,re,r,rp)
	--local tc=Duel.GetFirstTarget()
	if Duel.GetLP(tp)>=100 and e:GetHandler():GetAttack() >= 5000 then--tc:IsRelateToEffect(e) then
		if true then
			local lp=e:GetHandler():GetAttack()-5000
			Duel.Recover(tp,lp,REASON_EFFECT)
			local e1=Effect.CreateEffect(e:GetHandler())
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
			e1:SetRange(LOCATION_MZONE)
			e1:SetCode(EFFECT_SET_BASE_ATTACK)
			e1:SetValue(5000)
			e1:SetReset(RESET_EVENT+0x1fe0000)
			e:GetHandler():RegisterEffect(e1)
			local e2=e1:Clone()
			e2:SetCode(EFFECT_SET_BASE_DEFENSE)
			e:GetHandler():RegisterEffect(e2)
		end
	end
end

function s.materialvalcheck(e,c)
	local g=c:GetMaterial()
	Original_ATK=g:GetSum(Card.GetAttack)
	--Original_ATK=4000
	Original_DEF=g:GetSum(Card.GetDefense)
	--Original_DEF=4000
end
function s.atkdefop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:GetMaterialCount()==0 then return end
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_SET_BASE_ATTACK)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetValue(Original_ATK)
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SET_BASE_DEFENSE)
	e2:SetValue(Original_DEF)
	c:RegisterEffect(e2)
end
function s.sumoncon(e,c)
	if c==nil then return true end
	return Duel.GetLocationCount(c:GetControler(),LOCATION_MZONE)>-3 and Duel.GetTributeCount(c)>=3
end
function s.sumonop(e,tp,eg,ep,ev,re,r,rp,c)
	local g=Duel.SelectTribute(tp,c,3,3)
	c:SetMaterial(g)
	Duel.Release(g,REASON_SUMMON+REASON_MATERIAL)
end
function s.setcon(e,c)
	if not c then return true end
	return false
end
function s.cannotsettg(e,re,rp)
	local c=e:GetHandler()
	return c:IsAttribute(ATTRIBUTE_DEVINE)
end
function s.sumnotnegatedop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_TRIGGER)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTargetRange(LOCATION_GRAVE,LOCATION_GRAVE+LOCATION_MZONE,LOCATION_MZONE+LOCATION_SZONE,LOCATION_SZONE+LOCATION_HAND,LOCATION_HAND)
	e1:SetTarget(s.triggertg)
	e1:SetReset(RESET_EVENT+EVENT_SUMMON_SUCCESS)
	c:RegisterEffect(e1)
end
function s.triggertg(e,c)
	return not c:IsRace(RACE_DEVINE)
end
--function s.filter(c,e,tp)
	--return c:GetLevel()==4 and c:IsCanBeSpecialSummoned(e,0,tp,false,false)
--end
function s.nottributedval(c,tp)
 	return not c:IsControler(tp)
end
function s.nottributedcon(c,tp)
	return not c:IsControler(tp)
end
function s.notargetedval(e,te)
	return not te:GetHandler():IsAttribute(ATTRIBUTE_DEVINE)
end
function s.nodestroyedval(e,te)
	return not te:GetHandler():IsAttribute(ATTRIBUTE_DEVINE)
end
function s.togravecon(e,c)
	local c=e:GetHandler()
	return not c:IsCode(10000010)
end
function s.changebattlepositioncost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:GetHandler():GetFlagEffect(190000013)==1 and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_NORMAL)==SUMMON_TYPE_NORMAL 
	and e:GetHandler():GetAttackAnnouncedCount()==0 end
end
function s.changebattlepositionop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	Duel.ChangePosition(c,POS_FACEUP_DEFENSE,0,POS_FACEUP_ATTACK,0)
end
function s.changebattlepositionop2(e,tp,eg,ep,ev,re,r,rp)
	e:GetHandler():RegisterFlagEffect(190000013,RESET_EVENT+0xfc0000+RESET_PHASE+PHASE_END,0,1)
end
function s.specialsumtogravecon(e,tp,eg,ep,ev,re,r,rp)
	return bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL
end
function s.specialsumtogravetg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	Duel.SetOperationInfo(0,CATEGORY_TOGRAVE,e:GetHandler(),1,0,0)
end
function s.specialsumtograveop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) and c:IsFaceup() then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		--e1:SetReset(RESET_EVENT+0x1fe0000)
		c:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		--e2:SetReset(RESET_EVENT+0x1fe0000)
		c:RegisterEffect(e2)
		Duel.BreakEffect()
		Duel.SendtoGrave(c,REASON_EFFECT)
	end
end
function s.changebattletargetcon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local bt=Duel.GetAttackTarget()
	return c~=bt and bt:IsControler(tp) and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():IsDefensePos()
end
function s.changebattletargetop(e,tp,eg,ep,ev,re,r,rp)
	Duel.ChangeAttackTarget(e:GetHandler())
end
function s.pointtopointcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFlagEffect(tp,10000014)==0 and Duel.GetLP(tp)>1 
	and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():IsPreviousLocation(LOCATION_GRAVE) end
	Duel.RegisterFlagEffect(tp,10000012,RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN,0,1)
end
function s.pointtopointop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local LP=Duel.GetLP(tp)
	Duel.SetLP(tp,1)
	ATK=LP-1
	DEF=LP-1
	if c:IsFaceup() and c:IsRelateToEffect(e) then
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_SET_BASE_ATTACK)
	e1:SetValue(ATK+c:GetAttack())
	--e1:SetReset(RESET_EVENT+0x1ff0000)
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SET_BASE_DEFENSE)
	e2:SetValue(DEF+c:GetDefense())
	c:RegisterEffect(e2)
	end
end
function s.tributetopointcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.CheckReleaseGroup(tp,nil,1,e:GetHandler()) and Duel.GetFlagEffect(tp,10000012)==1 
	and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():IsPreviousLocation(LOCATION_GRAVE) end
end
function s.tributetopointop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local g=Duel.GetMatchingGroup(Card.IsReleaseable,tp,LOCATION_MZONE,0,e:GetHandler())
	local ATK=g:GetSum(Card.GetAttack)
	local DEF=g:GetSum(Card.GetDefense)
	Duel.Release(g,REASON_COST)
	if c:IsFaceup() and c:IsRelateToEffect(e) then
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_SET_BASE_ATTACK)
	e1:SetValue(ATK+c:GetAttack())
	--e1:SetValue(4500)
	--e1:SetReset(RESET_EVENT+0x1ff0000)
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SET_BASE_DEFENSE)
	e2:SetValue(DEF+c:GetDefense())
	--e2:SetValue(4500)
	c:RegisterEffect(e2)
	end
end
function s.costfilter(c)
	return c:IsCode(95286165) and c:IsAbleToGraveAsCost()
end
function s.defusioncost(e,tp,eg,ep,ev,re,r,rp,chk)
		if chk==0 then return Duel.IsExistingTarget(s.costfilter,tp,LOCATION_HAND+LOCATION_SZONE,0,1,e:GetHandler()) and Duel.GetFlagEffect(tp,10000012)==1 
		and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():IsPreviousLocation(LOCATION_GRAVE) and e:GetHandler():GetAttack()>0 end
		Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
		local g=Duel.SelectMatchingCard(tp,s.costfilter,tp,LOCATION_HAND+LOCATION_SZONE,0,1,1,nil)
		Duel.SendtoGrave(g,REASON_COST)
end
function s.defusionop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsFaceup() and c:IsRelateToEffect(e) then
		local ATK=c:GetAttack()
		local DEF=c:GetDefense()
		Duel.Recover(tp,ATK,REASON_EFFECT)
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetReset(RESET_EVENT+0x1fe0000)
		e1:SetCode(EFFECT_SET_BASE_ATTACK)
		e1:SetValue(-ATK)
		c:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_SET_BASE_DEFENSE)
		e2:SetValue(-DEF)
		c:RegisterEffect(e2)
		end
		if Duel.GetAttacker()==e:GetHandler() then
		Duel.NegateAttack()
	end
end
function s.iacost(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then return e:GetHandler():GetAttackAnnouncedCount()==0 and Duel.GetFlagEffect(tp,10000012)==1 and Duel.GetFlagEffect(tp,10000013)==0 
	and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():IsPreviousLocation(LOCATION_GRAVE) end
	Duel.RegisterFlagEffect(tp,10000013,RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN,0,1)
	end
function s.iaop(e,tp,eg,ep,ev,re,r,rp)
		local c=e:GetHandler()
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_EXTRA_ATTACK)
		--e1:SetReset(RESET_EVENT+0x1ff0000)
		e1:SetReset(RESET_EVENT+0x1fe0000)
		e1:SetValue(99)
		c:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_CANNOT_ATTACK)
		e2:SetCondition(s.atkcon)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e3:SetRange(LOCATION_MZONE)
		e3:SetCode(EFFECT_IMMUNE_EFFECT)
		--e3:SetReset(RESET_EVENT+0x1ff0000)
		e3:SetReset(RESET_EVENT+0x1fe0000)
		e3:SetValue(s.unaffectedval)
		c:RegisterEffect(e3)
		if Duel.GetTurnPlayer()~=tp then
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e4:SetRange(LOCATION_MZONE)
		e4:SetCode(EFFECT_CANNOT_TRIGGER)
		e4:SetTarget(s.iatrig)
		e4:SetReset(RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(c)
		e5:SetType(EFFECT_TYPE_FIELD)
		e5:SetRange(LOCATION_MZONE)
		e5:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
		e5:SetTargetRange(LOCATION_MZONE,0)
		e5:SetTarget(s.notattackannouce)
		e5:SetReset(RESET_EVENT+0x1ff0000)
		c:RegisterEffect(e5)
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_FIELD)
		e6:SetCode(EFFECT_CANNOT_M2)
		e6:SetRange(LOCATION_MZONE)
		e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
		e6:SetTargetRange(1,0)
		e6:SetReset(RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN)
		Duel.RegisterEffect(e6,tp)
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_DRAW or Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_STANDBY then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		end
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_MAIN1 then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		end
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_BATTLE then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		end
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_MAIN2 then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
	end
	end
end
function s.atkcon(e)
	return e:GetHandler():IsDirectAttacked()
end
function s.unaffectedval(e,te)
	return te:GetOwner()~=e:GetOwner()
end
function s.iatrig(e,c)
	return e:GetHandler()
end
function s.notattackannouce(e,c)
	return c~=e:GetHandler()
end
function s.godphoenixcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFlagEffect(tp,10000012)==0  and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL 
	and e:GetHandler():IsPreviousLocation(LOCATION_GRAVE) end
	Duel.RegisterFlagEffect(tp,10000014,RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN,0,1)
end
function s.godphoenixop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
		Duel.SendtoGrave(c,REASON_EFFECT)
		if Duel.GetLocationCount(tp,LOCATION_MZONE)<1 then return end
		if not Duel.IsPlayerCanSpecialSummonMonster(tp,110000014,0,0x21,0,0,10,RACE_DEVINE,ATTRIBUTE_DEVINE) then return end
		for i=1,1 do
		local token=Duel.CreateToken(tp,110000014)
		Duel.SpecialSummonStep(token,0,tp,tp,false,false,POS_FACEUP_ATTACK)
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e1:SetRange(LOCATION_MZONE)
		e1:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
		e1:SetValue(1)
		e1:SetReset(RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END)
		token:RegisterEffect(e1,true)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_AVOID_BATTLE_DAMAGE)
		token:RegisterEffect(e2,true)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_IMMUNE_EFFECT)
		e2:SetValue(s.selfdestruction)
		token:RegisterEffect(e2,true)
		local e3=Effect.CreateEffect(e:GetHandler())
		e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetRange(LOCATION_MZONE)
		e3:SetCode(EVENT_PHASE+PHASE_END)
		e3:SetCountLimit(1)
		e3:SetOperation(s.godphoenixendop)
		token:RegisterEffect(e3,true)
		--Incinerate
		local e4=Effect.CreateEffect(e:GetHandler())
		e4:SetDescription(aux.Stringid(190000013,0))
		e4:SetCategory(CATEGORY_DISABLE+CATEGORY_DESTROY)
		e4:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_IGNORE_IMMUNE)
		e4:SetType(EFFECT_TYPE_QUICK_O)
		e4:SetCode(EVENT_FREE_CHAIN)
		e4:SetHintTiming(TIMING_DAMAGE_STEP)
		e4:SetRange(LOCATION_MZONE)
		e4:SetCountLimit(1)
		e4:SetCost(s.inccost)
		e4:SetTarget(s.inctg)
		e4:SetOperation(s.incop)
		token:RegisterEffect(e4)
	end
	Duel.SpecialSummonComplete()
end
function s.selfdestruction(e,te)
	return not te:GetHandler():IsCode(110000014)
end
function s.godphoenixendop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_SELF_DESTROY)
	c:RegisterEffect(e1)
end
function s.inccost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.CheckLPCost(tp,1000) end
	Duel.PayLPCost(tp,1000)
end
function s.inctg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return Duel.IsExistingTarget(Card.IsDestructable,tp,0,LOCATION_MZONE,1,nil) end
	local g=Duel.GetMatchingGroup(Card.IsDestructable,tp,0,LOCATION_MZONE,nil)
	Duel.SetOperationInfo(0,CATEGORY_DESTROY,g,g:GetCount(),0,0)
end
function s.incop(e,tp,eg,ep,ev,re,r,rp)
		local c=e:GetHandler()
		local g=Duel.GetMatchingGroup(Card.IsDestructable,tp,0,LOCATION_MZONE,nil)
		local tc=g:GetFirst()
		while tc do
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		tc:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		tc:RegisterEffect(e2)
		tc=g:GetNext()
		Duel.BreakEffect()
		Duel.Destroy(g,REASON_EFFECT)
	end
end
function s.atkdefresetop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_SET_ATTACK_FINAL)
	e1:SetValue(c:GetBaseAttack())
	--e1:SetReset(RESET_EVENT+0x1fe0000)
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_SET_DEFENSE_FINAL)
	e2:SetValue(c:GetBaseDefense())
	--e2:SetReset(RESET_EVENT+0x1fe0000)
	e2:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e2)
end
function s.cryomancerfilter(c)
	return c:IsFaceup() and c:IsCode(23950192)
end
function s.cryomancercon(e)
	return Duel.IsExistingTarget(s.cryomancerfilter,0,LOCATION_MZONE,LOCATION_MZONE,1,e:GetHandler())
end
function s.cryomancerop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.cryomancerimmunefilter)
	c:RegisterEffect(e1)
end
function s.cryomancerimmunefilter(e,te)
	return te:GetHandler():IsCode(23950192)
end
function s.gorgonfilter(c)
	return c:IsFaceup() and c:IsCode(43426903)
end
function s.gorgoncon(e)
	return Duel.IsExistingTarget(s.gorgonfilter,tp,0,LOCATION_MZONE,1,nil)
end
function s.gorgonop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.gorgonimmunefilter)
	c:RegisterEffect(e1)
end
function s.gorgonimmunefilter(e,te)
	return te:GetHandler():IsCode(43426903)
end
function s.harpiefilter(e)
	local c=e:GetHandler()
	return c:IsFaceup() and c:IsCode(54415063)
end
function s.harpiecon(e)
	--return Duel.IsExistingTarget(s.harpiefilter,tp,0,LOCATION_MZONE,1,nil)
	return Duel.IsExistingTarget(s.harpiefilter,tp,0,LOCATION_MZONE,1,nil)
end
function s.harpieop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.harpieimmunefilter)
	c:RegisterEffect(e1)
end
function s.harpieimmunefilter(e,te)
	return te:GetHandler():IsCode(54415063)
end
function s.goraturtlefilter(c)
	return c:IsFaceup() and c:IsCode(80233946)
end
function s.goraturtlecon(e)
	return Duel.IsExistingTarget(s.goraturtlefilter,0,LOCATION_MZONE,LOCATION_MZONE,1,e:GetHandler())
end
function s.goraturtleop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.goraturtleimmunefilter)
	c:RegisterEffect(e1)
end
function s.goraturtleimmunefilter(e,te)
	return te:GetHandler():IsCode(80233946)
end
function s.defenderfilter(c)
	return c:IsFaceup() and c:IsCode(82498947)
end
function s.defendercon(e)
	return Duel.IsExistingTarget(s.defenderfilter,tp,0,LOCATION_MZONE,1,nil)
end
function s.defenderop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.defenderimmunefilter)
	c:RegisterEffect(e1)
end
function s.defenderimmunefilter(e,te)
	return te:GetHandler():IsCode(82498947)
end
function s.deltawingfilter(c)
	return c:IsFaceup() and c:IsCode(100000240)
end
function s.deltawingcon(e)
	return Duel.IsExistingTarget(s.deltawingfilter,tp,0,LOCATION_MZONE,1,nil)
end
function s.deltawingop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.deltawingimmunefilter)
	c:RegisterEffect(e1)
end
function s.deltawingimmunefilter(e,te)
	return te:GetHandler():IsCode(100000240)
end
function s.thousandeyesfilter(c)
	return c:IsFaceup() and c:IsCode(63519819)
end
function s.thousandeyescon(e)
	return Duel.IsExistingTarget(s.thousandeyesfilter,0,LOCATION_MZONE,LOCATION_MZONE,1,e:GetHandler())
end
function s.thousandeyesop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.thousandeyesimmunefilter)
	c:RegisterEffect(e1)
end
function s.thousandeyesimmunefilter(e,te)
	return te:GetHandler():IsCode(63519819)
end
function s.levelareafilter(c)
	return c:IsFaceup() and c:IsCode(3136426)
end
function s.levelareacon(e)
	return Duel.IsExistingTarget(s.levelareafilter,0,LOCATION_SZONE,LOCATION_SZONE,1,e:GetHandler())
end
function s.levelareaop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.levelareaimmunefilter)
	c:RegisterEffect(e1)
end
function s.levelareaimmunefilter(e,te)
	return te:GetHandler():IsCode(3136426)
end
function s.concealinglightfilter(c)
	return c:IsFaceup() and c:IsCode(12923641)
end
function s.concealinglightcon(e)
	return Duel.IsExistingTarget(s.concealinglightfilter,tp,0,LOCATION_SZONE,1,nil)
end
function s.concealinglightop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.concealinglightimmunefilter)
	c:RegisterEffect(e1)
end
function s.concealinglightimmunefilter(e,te)
	return te:GetHandler():IsCode(12923641)
end
function s.spiderslairfilter(c)
	return c:IsFaceup() and c:IsCode(26640671)
end
function s.spiderslaircon(e)
	return Duel.IsExistingTarget(s.spiderslairfilter,tp,0,LOCATION_SZONE,1,nil)
end
function s.spiderslairop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.spiderslairimmunefilter)
	c:RegisterEffect(e1)
end
function s.spiderslairimmunefilter(e,te)
	return te:GetHandler():IsCode(26640671)
end
function s.messengerfilter(c)
	return c:IsFaceup() and c:IsCode(44656491)
end
function s.messengercon(e)
	return Duel.IsExistingTarget(s.messengerfilter,0,LOCATION_SZONE,LOCATION_SZONE,1,e:GetHandler())
end
function s.messengerop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.messengerimmunefilter)
	c:RegisterEffect(e1)
end
function s.messengerimmunefilter(e,te)
	return te:GetHandler():IsCode(44656491)
end
function s.revealinglightfilter(c)
	return c:IsFaceup() and c:IsCode(72302403)
end
function s.revealinglightcon(e)
	return Duel.IsExistingTarget(s.revealinglightfilter,tp,0,LOCATION_SZONE,1,nil)
end
function s.revealinglightop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.revealinglightimmunefilter)
	c:RegisterEffect(e1)
end
function s.revealinglightimmunefilter(e,te)
	return te:GetHandler():IsCode(72302403)
end
function s.burninglightfilter(c)
	return c:IsFaceup() and c:IsCode(93087299)
end
function s.burninglightcon(e)
	return Duel.IsExistingTarget(s.burninglightfilter,tp,0,LOCATION_SZONE,1,nil)
end
function s.burninglightop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.burninglightimmunefilter)
	c:RegisterEffect(e1)
end
function s.burninglightimmunefilter(e,te)
	return te:GetHandler():IsCode(93087299)
end
function s.finalordersfilter(c)
	return c:IsFaceup() and c:IsCode(52503575)
end
function s.finalorderscon(e)
	return Duel.IsExistingTarget(s.finalordersfilter,0,LOCATION_SZONE,LOCATION_SZONE,1,e:GetHandler())
end
function s.finalordersop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.finalordersimmunefilter)
	c:RegisterEffect(e1)
end
function s.finalordersimmunefilter(e,te)
	return te:GetHandler():IsCode(52503575)
end
function s.morphtronicbindfilter(c)
	return c:IsFaceup() and c:IsCode(85101228)
end
function s.morphtronicbindcon(e)
	return Duel.IsExistingTarget(s.morphtronicbindfilter,tp,0,LOCATION_SZONE,1,nil)
end
function s.morphtronicbindop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.morphtronicbindimmunefilter)
	c:RegisterEffect(e1)
end
function s.morphtronicbindimmunefilter(e,te)
	return te:GetHandler():IsCode(85101228)
end
function s.gravitybindfilter(c)
	return c:IsFaceup() and c:IsCode(85742772)
end
function s.gravitybindcon(e)
	return Duel.IsExistingTarget(s.gravitybindfilter,0,LOCATION_SZONE,LOCATION_SZONE,1,e:GetHandler())
end
function s.gravitybindop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_IMMUNE_EFFECT)
	e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
	e1:SetValue(s.gravitybindimmunefilter)
	c:RegisterEffect(e1)
end
function s.gravitybindimmunefilter(e,te)
	return te:GetHandler():IsCode(85742772)
end